site_name: carto-flow
repo_url: https://github.com/fkloosterman/carto-flow
site_url: https://fkloosterman.github.io/carto-flow
site_description: This is a library for creating cartographs.
site_author: FKloosterman
edit_uri: edit/main/docs/
repo_name: fkloosterman/carto-flow
copyright: Maintained by <a href="https://fkloosterman.com">fkloosterman</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/carto_flow"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fkloosterman/carto-flow
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/carto-flow

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
